### ISSUE TITLE
Customization, fonts and systray

### ISSUE THREAD

**Issue by 4e6** [wavexx/screenkey#13]
It would be nice to be able to customize:
- background color `--bgcolor #0F0F0F`
- font color `--fontcolor #FFFFFF`
- do not show system tray icon `--no-systray`

**Comment by 4e6** [comment]
I've already partially implemented it for myself and will try to finish it shortly. If you have some thoughts on the naming of arguments or whatever, please me know.

**Comment by wavexx** [comment]
On 07/09/15 11:12, Dmitry Bushev wrote:

> It would be nice to be able to customize:
> - background color |--bgcolor #0F0F0F|
> - font color |--fontcolor #FFFFFF|

I'm curious at what colors would you use?

When I was introduced to screenkey (as a viewer), I wouldn't have
appreciated anything else. I like it's so readable by default.

I was even thinking to add control over the transparency, but only allow

> 0.7 and above for the same reason.

But maybe there's a better reason?

**Comment by 4e6** [comment]
I'm still experimenting with different options. My current setup is a floating fixed window above i3bar. It means that I need to slightly adjust colors to match i3bar colorscheme, see screenshot
![2015-09-11-111723_2560x1440_scrot](https://cloud.githubusercontent.com/assets/357683/9810153/04d83014-5877-11e5-8b76-b40a227cf0ae.png)

**Comment by wavexx** [comment]
On 11/09/15 10:24, Dmitry Bushev wrote:

> I'm still experimenting with different options. My current setup is a
> floating fixed window above i3bar. It means that I need to slightly
> adjust colors to match i3bar colorscheme, see screenshot

That's nice! But I hope you're not going to use that for a screencast
and/or teaching ;). It's really _very_ small.

**Comment by 4e6** [comment]
I found myself more productive in vim and emacs when I see what I am typing. Because when you see something like `jjjjjjjjjjjjjjjjjjjjjjjjj` browsing vim, there is definitely a way to improve yourself :)
