### ISSUE TITLE
screenkey does not work with i3-wm

### ISSUE THREAD

**Issue by zenny** [wavexx/screenkey#16]
Screenkey does not work with i3 window manager despite appending:
# for_window [title="^screenkey"] floating enable

in the config file. My machine has the following:

$ screenkey --version
0.2

$ i3 --version
i3 version 4.11-5-g6d385e6 (2015-10-02, branch "master") © 2009 Michael Stapelberg and contributors

$ lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty

**Comment by zenny** [comment]
This comment is still applicable.

https://bugs.launchpad.net/screenkey/+bug/848031/comments/4

**Comment by zenny** [comment]
This works as desired  +1: 

https://github.com/muflax/screenkey

https://launchpad.net/screenkey/0.2/0.2.0/+download/screenkey_0.2_all.deb

**Comment by wavexx** [comment]
On 25/10/15 10:20, zenny wrote:

> Screenkey does not work with i3 window manager despite appending:
> 
> # for_window [title="^screenkey"] floating enable
> 
> in the config file. My machine has the following:
> 
> $ screenkey --version
> 0.2

Note that screenkey in this repository is at 0.7 ;)

**Comment by zenny** [comment]
Sorry for the oversight. this work works better in some ways.

However, how can one show mouse clicks like how key-mon shows?

**Comment by wavexx** [comment]
On 25/10/15 15:43, zenny wrote:

> Sorry for the oversight. this work works better in some ways.
> 
> However, how can one show mouse clicks like how key-mon shows?

Not yet.

I use screenkey together with key-mon for this reason.

**Comment by wavexx** [comment]
Closing this, I'll open a new issue for mouse clicks, since this is something that I'll also like to implement in the future.

**Comment by zenny** [comment]
@wavexx  Thanks for considering https://github.com/wavexx/screenkey/issues/18 - a desired feature!
