### ISSUE TITLE
Visible "Click"

### ISSUE THREAD

**Issue by wavexx** [wavexx/screenkey#18]
It's very often useful to highlight where the mouse has clicked, and also show which mouse button and keyboard modifiers have been pressed.

I'm using `key-mon` just to do that, and the way `key-mon` shows clicks/modifiers is pretty decent. Regardless, it would be just better to integrate the same feature in screenkey, so that we can reuse the same modifier/keyboard handling (and same visual style as well).

See issue #16

**Comment by zenny** [comment]
Thanks for pointing out a desired feature. key-mon, like you say, has pretty decent clicks display. Look forward to the new feature.

**Comment by wavexx** [comment]
Closing in favor or the more detailed #43
