### ISSUE TITLE
Fedora: E: invalid-desktopfile

### ISSUE THREAD

**Issue by ghost** [wavexx/screenkey#20]
Error -> desktop-file-validate

```
screenkey.noarch: E: invalid-desktopfile /usr/share/applications/screenkey.desktop value "0.8" for key "Version" in group "Desktop Entry" is not a known version
screenkey.noarch: E: invalid-desktopfile /usr/share/applications/screenkey.desktop value "GNOME;Utility" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing character

```

**Comment by wavexx** [comment]
Can you help providing a better desktop file?
I admit I'm not using any DE, so I never actually use menus.

I don't know, for example, if there's a nice way to link to the README, which contains some useful tips for usage. I had some users ask some questions which are already answered in there, but given there's no real "help" file yet, maybe a menu link would be good.

**Comment by ghost** [comment]
@wavexx I'm sorry, I do not understand English.

**Comment by ghost** [comment]
:+1:
