### ISSUE TITLE
screenkey need icons

### ISSUE THREAD

**Issue by ghost** [wavexx/screenkey#21]
@wavexx hi, need icon
![2015-11-16 16-48-56](https://cloud.githubusercontent.com/assets/13280183/11183432/b5dd79e8-8c82-11e5-9e85-06c7b4a9b113.png)

**Comment by wavexx** [comment]
I'm really not good at icons. Any takers?

**Comment by ghost** [comment]
@wavexx I changed the icon and now everything is fine
![2015-11-16 17-52-35](https://cloud.githubusercontent.com/assets/13280183/11184893/19a620ee-8c8b-11e5-85ba-1bbbe390d1e2.png)
