### ISSUE TITLE
Support meta keys by themselves

### ISSUE THREAD

**Issue by rothgar** [wavexx/screenkey#22]
This is great. It would be nice if it would show modifier keys pressed at the moment they are pressed instead of when an additional key is pressed.

For example, in gnome-shell pressing the super key (by itself) will bring up the dashboard. This is done a lot but I couldn't figure out a preference to show when the super key is pressed by itself.

**Comment by wavexx** [comment]
On 22/11/15 08:58, Justin Garrison wrote:

> For example, in gnome-shell pressing the super key (by itself) will
> bring up the dashboard. This is done a lot but I couldn't figure out a
> preference to show when the super key is pressed by itself.

The current output looks good for typing, but it's not convenient for
modifier status (it would just output gobs of keys all the time).

Screenkey needs to use a different window for this kind of stuff,
showing the status of the modifiers only, pretty much like how key-mod
does already.
