### ISSUE TITLE
Static HTML files for each image, and social sharing feature request

### ISSUE THREAD

**Issue by ghost** [wavexx/screenkey#26]
fgallery is excellent maybe the best quick gallery script there is.

I would like to propose social sharing feature. With option like --social, the pictures would get one beautiful extra HTML file, that is made by template.html (to be done). In such template, one would include meta tags, ans schema tags, Twitter cards, Facebook for better sharing. 

Something like 

```
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>{$page_title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel=icon href="{$faviconico}" sizes="60x60" type="image/png"/>

    <!-- Standard Meta Tags -->
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="generator" content="{$generator}"/>
    <meta name="author" content="{$page_author}"/>
    <meta name="keywords" content="{$page_keywords}"/>
    <meta name="description" content="{$page_description}"/>
    <!-- Standard Meta Tags -->

    <!-- Google Schema.org -->
    <meta itemprop="name" content="{$page_title}" /> 
    <meta itemprop="description" content="{$page_description}" />  
    <meta itemprop="image" content="{$page_ogimage}" /> 
    <!-- Google Schema.org -->

    <!-- Facebook Open Graph -->
    <meta property="og:title" content="{$page_title}"/>
    <meta property="og:type" content="{$page_ogtype}"/>
    <meta property="og:url" content="{$current_url}"/>
    <meta property="og:image" content="{$page_ogimage}"/>
    <meta property="og:site_name" content="{$areas_name}"/>
    <meta property="og:description" content="{$page_description}"/>
    <meta property="fb:admins" content="{$fb_admins}"/>
    <!-- Facebook Open Graph -->

    <!-- Twitter Card -->
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:site" content="@{$twitter_user}"/>
    <meta name="twitter:creator" content="@{$twitter_user}"/>
    <meta name="twitter:title" content="{$page_title}"/>
    <meta name="twitter:description" content="{$page_description}"/>
    <meta name="twitter:image" content="{$page_ogimage}"/>
    <!-- Twitter Card -->
```

The file should look **about the same** as the gallery. But it would be static, that it can be shared on social networks. If user clicks on the small thumbnail, user would be brought back to the original Javascript fgallery picture.

On each Javascript fgallery picture, there would be some modifiable social sharing buttons, such as Facebook, Google, Twitter, Stubmleupon. It should be of course fast, not bloated.

Social sharing buttons would not share the Javascript directory like /gallery, but rather a single picture in the HTML file, something like /gallery/static/picture-001.html --- and when user arrives here, he would see basically the same design, but it would be static file. After clicking on forward, he would be moved to next picture but in the directory /gallery/#002 for example. Or after clicking on thumbnail, user would be moved to /gallery/#017 which is original fgallery.

In that manner, there would be static files, which is good for SEO, good for social networks, and fgallery too.

**Comment by wavexx** [comment]
wrong project
