### ISSUE TITLE
Corrupt archive/repo

### ISSUE THREAD

**Issue by vishusingh** [wavexx/screenkey#28]
I've been unable to unzip the downloaded archive, returns an error “21 - is a directory” which it certainly is not.

Tried cloning the repo, but it has several unstaged files, a hard reset to the last commit also fails to reset the tree. Seems like the repo is corrupted somehow, suggestions?

**Comment by wavexx** [comment]
On Tue, Feb 23 2016, vishusingh notifications@github.com wrote:

> I've been unable to unzip the downloaded archive.
> 
> Tried cloning the repo, but it has several unstaged files, a hard reset to the
> last commit also fails to reset the tree. Seems like the repo is corrupted
> somehow, suggestions?

That's doubly odd. I just cloned/checked the github repo and it matches
all checksums.

I suspect you might have ram issues, or a corrupt filesystem.

**Comment by wavexx** [comment]
Were you able to track this down?

**Comment by wavexx** [comment]
.. silently closing...
