### ISSUE TITLE
Settings dialog

### ISSUE THREAD

**Issue by wavexx** [wavexx/screenkey#29]
Aside from the overlong/misplaced look, the code... needs to be trashed. There are settings (such as "ignored" keys) which cannot be changed interactively. Adding too much _new_ code to the existing mess is a bad idea.

10 karma points for the brave soul that can help in re-doing the UI in glade.

**Comment by bilelmoussaoui** [comment]
Using gtk3 or gtk2?

**Comment by wavexx** [comment]
For the moment, using gtk2. Migrating the ui to gtk3 is trivial anyway, and I don't see any new widget in gtk3 that would make it better.

**Comment by bilelmoussaoui** [comment]
Well, gtk2 is dead...Gtk3 has better styling support and a lot of awesome features :)

**Comment by wavexx** [comment]
On Wed, Aug 30 2017, Bilal Elmoussaoui wrote:
> Well, gtk2 is dead...Gtk3 has better styling support and a lot of
> awesome features :)

I don't know, I hate GTK3 open dialogs with a passion for example, they
keep getting worse. GTK3 looks good, but behaves badly. As a developer,
I pretty much abandoned gtk in favor of qt because of this.

But that being aside, when using glade upgrading the ui to gtk3 is just
a save operation. There are still some dependencies on gtk2 in screenkey
that I couldn't rework yet, so it's just a question of time: if it's
done in gtk2, it's going to get it quickly, in gtk3 it will have to wait
a bit until the migration to gtk3 is complete.

In any case, the glade ui would be helpful to remove the current code.
