### ISSUE TITLE
Way around using setuptools-git

### ISSUE THREAD

**Issue by hotice** [wavexx/screenkey#30]
Is there a way around using setuptools-git? I'm asking because I maintain ScreenKey in my PPA for Ubuntu, Linux Mint, etc., and the Launchpad PPA build system doesn't allow downloading external tools, so the build system can't download setuptools-git, and thus, I can't build the latest screenkey 0.9 package, which depends on setuptools-git in setup.py, in the PPA.

Thanks!

**Comment by hotice** [comment]
I just removed "setuptools-git" from setup.py and everything seems to work ok. I assume doing this doesn't affect the app in any way?

**Comment by wavexx** [comment]
On Mon, May 16 2016, Andrew notifications@github.com wrote:

> I just removed "setuptools-git" from setup.py and everything seems to work ok. I assume doing this doesn't affect the app in any way?

Check if language files are still built and installed correctly.

**Comment by hotice** [comment]
I see language files in the package built without setuptools-git for uk, fr, zh and es - screenshot: 
![image](https://cloud.githubusercontent.com/assets/325449/15289100/809fe4e8-1b78-11e6-9aeb-97c64abb3c36.png)

I assume it looks ok?

**Comment by wavexx** [comment]
Looks good. I removed it from the package_requires. I use it to generate the package with sdist, and while it's not required for build (or to be written in setup.py at all), sdist without setuptools-git installed will omit the language data. 

On a related note, how do you feel about depending on python-glade?
I'd like to remove some crufty code and use something more modern.

**Comment by hotice** [comment]
Thanks! Regarding python-glade, I'm not a software developer, so I can't comment on it :) From a packager point of view, anything that's available in the official repositories is ok :)

**Comment by wavexx** [comment]
Ok, closing this then.

Strange that setuptools-git isn't. It's a pretty common dependency in python packages nowdays.
Or maybe not for end-user programs...

**Comment by hotice** [comment]
Both in Launchpad PPAs and in the official Ubuntu repositories, a package can be built only if its dependencies are available in the official repositories, and setuptools-git isn't...
