### ISSUE TITLE
Upload to pipy for easier installation

### ISSUE THREAD

**Issue by timthelion** [wavexx/screenkey#31]
It would be nice to be able to install this via `pip install screenkey`.

**Comment by wavexx** [comment]
On Sat, Jul 02 2016, Timothy Hobbs notifications@github.com wrote:

> It would be nice to be able to install this via `pip install screenkey`.

I'm not super-fond of uploading programs which are not modules on pypi
(that's _not_ what I'm looking for in pypi).

Other opinions?

**Comment by mbrgm** [comment]
I wanted to use some mechanisms, which are implemented in screenkey, to create a lightweight text snippets/expansion program. Of course, pulling in the whole _program_ is not what I'd want to do in the first place, but it would give me a quick way to use the parts I need without copy-pasting.

Maybe some functions could be extracted to a proper module, but this might be overkill for my use case.

**Edit:** For the 'program on pypi part': It seems that lots of projects choose this way for easier installation nowadays. Depends on whether you see pypi as a 'module' vs. 'general python package' registry.

**Comment by wavexx** [comment]
On Sun, Jul 24 2016, Marius Bergmann notifications@github.com wrote:

> I wanted to use some mechanisms, which are implemented in screenkey,
> to create a lightweight text snippets/expansion program. Of course,
> pulling in the whole _program_ is not what I'd want to do in the first
> place, but it would give me a quick way to use the parts I need
> without copy-pasting.

Now you made me curious :)

**Comment by mbrgm** [comment]
My plan is to create a simple script, which monitors keystrokes and then expands configurable key sequences: Say you're typing `mail#`, this would then be expanded to `john@example.com`.

For the montioring part, I wanted to build upon the capabilities of screenkey, which gives me exactly the output/key sequences I'm looking for.

**Comment by wavexx** [comment]
On Sun, Jul 24 2016, Marius Bergmann notifications@github.com wrote:

> My plan is to create a simple script, which monitors keystrokes and
> then expands configurable key sequences: Say you're typing `mail#`,
> this would then be expanded to `john@example.com`.
> 
> For the montioring part, I wanted to build upon the capabilities of
> screenkey, which gives me exactly the output/key sequences I'm looking
> for.

Nice.

I was wondering if this could be built into a gtk-im-module (as this
would allow you access the content of the field being edited), but yeah,
on the other hand this approach works independently of the widget set.

**Comment by mbrgm** [comment]
@wavexx So will you consider uploading to pypi or not?

**Comment by wavexx** [comment]
On Tue, Jul 26 2016, Marius Bergmann notifications@github.com wrote:

> @wavexx So will you consider uploading to pypi or not?

In this case the relevant part would be only the current "inputlistener"
right?

**Comment by wavexx** [comment]
I decided against this. I simply don't have time to support just the input module as of yet. There's some shuffling ahead too, for mouse interaction. Pick the module you need out of screenkey for now, it's more sensible.
