### ISSUE TITLE
On modifiers only mode it also shows the window

### ISSUE THREAD

**Issue by tunnckoCore** [wavexx/screenkey#32]
And it is empty, which not looks cool... Any combination with other options? hm.

**Comment by wavexx** [comment]
On Sat, Jul 02 2016, Charlike Mike Reagent notifications@github.com wrote:

> And it is empty, which not looks cool... Any combination with other options? hm.

Could you describe a bit more what do you do to trigger the window
showing up, and maybe attach your ~/.config/screenkey.json as well?

**Comment by tunnckoCore** [comment]
The config is the default + "modifiers only" option checked. And when when I type something it shows the black full width line but empty. When I use some of the modifiers all is okey.

http://sendvid.com/2n2hymkf

**Comment by wavexx** [comment]
On Sat, Jul 02 2016, Charlike Mike Reagent notifications@github.com wrote:

> The config is the default + "modifiers only" option checked. And when
> when I type something it shows the black full width line but empty.
> When I use some of the modifiers all is okey.
> 
> http://sendvid.com/2n2hymkf

Thanks. I remember fixing this behavior in an earlier release, are you
running 0.9 or master?

I cannot reproduce this on my machine.

If you could run "screenkey -d" in a terminal and send the output it
would be great (just pressing a couple of keys before stopping it is
enough).

**Comment by tunnckoCore** [comment]
> are you running 0.9 or master?

installed through ArchLinux's AUR (yaourt) - it is 0.8

```
% ❯ screenkey -d                                                                                          July 03  01:46:55
/usr/lib/python2.7/site-packages/Screenkey/screenkey.py:69: GtkWarning: Unable to locate theme engine in module_path: "adwaita",
  gtk.Window.__init__(self, gtk.WINDOW_POPUP)
DEBUG:Screenkey:Options loaded.
DEBUG:Screenkey:Restarting LabelManager.
DEBUG:Screenkey:Thread started.
DEBUG:Screenkey:Restarting LabelManager.
DEBUG:Screenkey:Thread stopped.
DEBUG:Screenkey:Thread started.
DEBUG:Screenkey:Modifiers only changed: True.
DEBUG:Screenkey:Using StatusIcon.
dDEBUG:Screenkey:Key pressed    100(ks): 'd' (d, mask: 00010000)
DEBUG:Screenkey:Label updated: u''.
aDEBUG:Screenkey:Key pressed     97(ks): 'a' (a, mask: 00010000)
DEBUG:Screenkey:Label updated: u''.
DEBUG:Screenkey:Key released   100(ks): d
DEBUG:Screenkey:Key released    97(ks): a
dDEBUG:Screenkey:Key pressed    100(ks): 'd' (d, mask: 00010000)
DEBUG:Screenkey:Label updated: u''.
DEBUG:Screenkey:Key released   100(ks): d
DEBUG:Screenkey:Key pressed  65515(ks): None (Super_L, mask: 00010000)
DEBUG:Screenkey:Key pressed    102(ks): 'f' (f, mask: 01010000)
DEBUG:Screenkey:Label updated: u'<u>\u200cSuper+f</u>'.
DEBUG:Screenkey:Key released   102(ks): f
DEBUG:Screenkey:Key released 65515(ks): Super_L
DEBUG:Screenkey:Key pressed  65307(ks): u'\x1b' (Escape, mask: 00010000)
DEBUG:Screenkey:Label updated: u'\u200cSuper+f'.
DEBUG:Screenkey:Key released 65307(ks): Escape
DEBUG:Screenkey:Key pressed  65507(ks): None (Control_L, mask: 00010000)
^C%
```

![2016-07-03-01 49 50_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/16542791/8db9ca3c-40c0-11e6-8f82-6e12d4cb5565.png)

**Comment by wavexx** [comment]
On Sun, Jul 03 2016, Charlike Mike Reagent notifications@github.com wrote:

> > are you running 0.9 or master?
> 
> installed through ArchLinux's yaourt

Out of curiosity, what windowmanager is this?

> DEBUG:Screenkey:Modifiers only changed: True.
> DEBUG:Screenkey:Using StatusIcon.
> dDEBUG:Screenkey:Key pressed    100(ks): 'd' (d, mask: 00010000)
> DEBUG:Screenkey:Label updated: u''.
> aDEBUG:Screenkey:Key pressed     97(ks): 'a' (a, mask: 00010000)
> DEBUG:Screenkey:Label updated: u''.
> DEBUG:Screenkey:Key released   100(ks): d

Somehow the mask is wrong, as if Alt is stuck, which is puzzling since
it's not shown anyway.

Any special keyboard setup/remapping you're using?
IBUS or FCITX running?

**Comment by tunnckoCore** [comment]
i3wm

> Any special keyboard setup/remapping you're using?

Don't think so.

> IBUS or FCITX running?

Don't know. How to check? I think IBUS.

Nothing so special really. Just normal europe keyboard and archlinux. Nothing custom.

**Comment by wavexx** [comment]
Try installing screenkey from the current master repository. I checked now, and the change I was discussing has been rolled into 0.9.

**Comment by tunnckoCore** [comment]
Hm. Okey, I'll try to install the git version and report back.

**Comment by tunnckoCore** [comment]
@wavexx 

``` sh
~/screenkey master
% 1 ❯ sudo ./setup.py install                                                                              July 05, 01:57:19
Traceback (most recent call last):
  File "./setup.py", line 2, in <module>
    from setuptools import setup
ImportError: No module named 'setuptools'
~/screenkey master
% 1 ❯ yaourt setuptools
2 extra/python2-setuptools 1:24.0.2-1 [installed]
    Easily download, build, install, upgrade, and uninstall Python packages
```

Can you update the AUR package to the latest version? Or it is that screenkey-git 0.3?

``` sh
% ❯ yaourt screenkey                                                                                   July 05, 02:01:15
1 aur/screenkey 0.8-1 (Out of Date) (63) (3.22)
    Screencast tool to show your keys inspired by Screenflick, based on key-mon. Active fork with new features.
2 aur/screenkey-git 0.3.67216f6-1 (5) (0.75)
    Screencast tool to show your keys inspired by Screenflick, based on key-mon. Active fork with new features.
==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
==> -------------------------------------------------------
==> 
```

**Comment by wavexx** [comment]
I'm not the maintainer of the AUR package, but if you install the dependencies (setuptools, python-gtk and python-distutils-extra) you can just test screenkey by running it directly via `./screenkey -d`.

**Comment by wavexx** [comment]
Any luck?

**Comment by tunnckoCore** [comment]
@wavexx nope, i have setuptools installed 

```
% ❯ yaourt setuptools                                                                                      July 07, 19:44:41
1 extra/python-setuptools 1:24.0.2-1
    Easily download, build, install, upgrade, and uninstall Python packages
2 extra/python2-setuptools 1:24.0.2-1 [installed]

```

maybe should install python-setuptools, idk, don't have time currently. maybe i'll try after few days more deeply.

**Comment by wavexx** [comment]
On Thu, Jul 07 2016, Charlike Mike Reagent notifications@github.com wrote:

> @wavexx nope, i have setuptools installed

Did you try to run ./screenkey directly from source?
You should already have all the required runtime components.

**Comment by tunnckoCore** [comment]
Yea, tried and it was some error again about `setuptools`.

**Comment by wavexx** [comment]
AUR has now 0.9.

**Comment by wavexx** [comment]
Ping @tunnckoCore

**Comment by tunnckoCore** [comment]
Oh sorry, didn't seen that from Feb 4. And I can't test now.

**Comment by wavexx** [comment]
Ping @olstenlarck again

**Comment by tunnckoCore** [comment]
Yup seems right now :) Tested and it appears on AUR too :)

**Comment by wavexx** [comment]
Ok!
