### ISSUE TITLE
show password :) ?!

### ISSUE THREAD

**Issue by 2020s2020** [wavexx/screenkey#35]
Hi
When I run a command such as "sudo apt upgrade" and sys ask me password, screenkey show my password!
How I can change this setting??

**Comment by wavexx** [comment]
On Mon, Oct 31 2016, saeed cs wrote:

> Hi
> When I run a command such as "sudo apt upgrade" and sys ask me password, screenkey show my password!
> How I can change this setting??

Screenkey has no way to know you're inserting a password.

You should disable screenkey temporarily before starting to insert
passwords.

You can do this by pressing both control keys at the same time.
Screenkey will pause without showing any info.

After you typed your password, press both keys again to resume
screenkey.

**Comment by 2020s2020** [comment]
> Screenkey has no way to know you're inserting a password.
> 
> You should disable screenkey temporarily before starting to insert
> passwords.
> 
> You can do this by pressing both control keys at the same time.
> Screenkey will pause without showing any info.
> 
> After you typed your password, press both keys again to resume
> screenkey.

Thanks for your attention.
Actually, I defined shortcut for start and stop Screenkey immediately after my post.
I hoped this topic be helpfull.

Be fun

**Comment by wavexx** [comment]
Closing, as there's no easy way to "hide" passwords without user help.
