### ISSUE TITLE
Elementary OS cannot install

### ISSUE THREAD

**Issue by jrock2004** [wavexx/screenkey#36]
Cloned the repo and did the install. When I try to run the program I get the following error

![screenshot from 2016-11-15 17 24 18](https://cloud.githubusercontent.com/assets/655716/20326816/6038a1de-ab58-11e6-9395-a2dccedde188.png)

**Comment by wavexx** [comment]
Do you know what input method are you using? ibus/fcitx?

The first errors are related to gtk (you're at least missing the gtk2-engines-pixbuf package).
The last error ("cannot initialize input method") is usually a sign of improperly configured keyboard/im settings.

**Comment by jrock2004** [comment]
I installed the gtk2 app. I am not sure which input method I am using, 

![image](https://cloud.githubusercontent.com/assets/655716/20328989/c3a0789a-ab63-11e6-8899-2874ba179880.png)

**Comment by wavexx** [comment]
Do you know if you're using ibus?
Can you show the output of:

```
pgrep ibus-daemon
env |grep IM
```

**Comment by jrock2004** [comment]
First command came up empty. The second command gave me this

```
⇨ env | grep IM                                                                                                       
QT_IM_MODULE=ibus
XDG_RUNTIME_DIR=/run/user/1000
REPORTTIME=10
```

**Comment by mrmakr** [comment]
I have the same problem:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/xx/screenkey/Screenkey/inputlistener.py", line 330, in run
    self._kbd_init()
  File "/home/xx/screenkey/Screenkey/inputlistener.py", line 266, in _kbd_init
    raise Exception("Cannot initialize input method")
Exception: Cannot initialize input method



pgrep ibus-daemon
env |grep IM
gives:
QT_IM_MODULE=xim
CLUTTER_IM_MODULE=xim
GTK_IM_MODULE=xim
QT4_IM_MODULE=xim

However 0.2 works, but crashes when i click the tray icon... Im on debian strech
edit: got it working with: screenkey -d --show-settings --no-detach

**Comment by wavexx** [comment]
Please create a separate report if you're not on elementary os.

**Comment by peteruithoven** [comment]
I'm also running into this issue on  ElementaryOS. 
```
$ ./screenkey
peteruithoven@xps:~/Downloads/screenkey-0.9$ Gtk-Message: Failed to load module "pantheon-filechooser-module"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/peteruithoven/Downloads/screenkey-0.9/Screenkey/keylistener.py", line 245, in run
    raise Exception("Cannot initialize input method")
Exception: Cannot initialize input method
```

```
$ env | grep IM                                                                                                       
QT_IM_MODULE=ibus
XDG_RUNTIME_DIR=/run/user/1000
REPORTTIME=10
```

Just in case it's useful:
![screenshot from 2017-05-14 02 36 30](https://cloud.githubusercontent.com/assets/523210/26030264/2d88e310-384e-11e7-8d2c-c7bb91b1b581.png)

**Comment by wavexx** [comment]
On Sun, May 14 2017, Peter Uithoven wrote:
> I'm also running into this issue on  ElementaryOS.

Did you customize the locale of ElementaryOS?
Is this the usual en_US, or anything special?

**Comment by peteruithoven** [comment]
![image](https://cloud.githubusercontent.com/assets/523210/26033883/22842a54-38b4-11e7-9903-ce9bc3476e5c.png)
The Language & Region list was empty for some reason. I tried adding English I then got a notification that I still had to install some things, which I did. It requested me to logout and login again. But now it's empty again. And I still get the same error when starting screenkey. 
I'll look into the empty languages list issue. (opened: https://github.com/elementary/switchboard-plug-locale/issues/21)

Running `locale` gives:  
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=
```

I tried setting Formats to United States as well, resulting in the following locale, but that still gives the same error when starting screenkey. 
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

**Comment by wavexx** [comment]
Ok, I tried to use elementaryos inside a VM, and I got the same problem.
Can you try to run:

    unset XMODIFIERS
    ./screenkey -d

from the latest git sources?

**Comment by wavexx** [comment]
It seems that ElementaryOS presets ibus as the default input method without actually running ibus. The required configuration variables are also not completely set (GTK_IM_MODULES is missing), and ibus is left unconfigured as well.

Unsetting XMODIFIERS fixes screenkey for me, but the setup is broken in ElementaryOS itself.
Somebody should file a bug against ElementaryOS and cite this page please.

**Comment by peteruithoven** [comment]
Could it be that this issue only occors when starting screenkey from a terminal? I've tried installing screenkey again and I can actually start it using the icon.

**Comment by peteruithoven** [comment]
When it starts however, it almost never works however. I've tried understanding when it does work but haven't been able to figure it out.

**Comment by wavexx** [comment]
Did you try to run it in the terminal after running ``unset XMODIFIERS``?
It can be that the environment flags are set differently when running it from the icon, however this is still a bug in ElementaryOS that you should report if you want anybody to pay attention.

**Comment by peteruithoven** [comment]
That works!

```
$ unset XMODIFIERS
$ screenkey -d
Gtk-Message: Failed to load module "pantheon-filechooser-module"
DEBUG:Screenkey:Options loaded.
DEBUG:Screenkey:Restarting LabelManager.
DEBUG:Screenkey:Thread started.
DEBUG:Screenkey:Using AppIndicator.
fDEBUG:Screenkey:Key pressed    102(ks): 'f' (f, mask: 00000000)
DEBUG:Screenkey:Label updated: u'\u200c<u>f</u>'.
DEBUG:Screenkey:Key released   102(ks): f
aDEBUG:Screenkey:Key pressed     97(ks): 'a' (a, mask: 00000000)
DEBUG:Screenkey:Label updated: u'\u200cf\u200c<u>a</u>'.
DEBUG:Screenkey:Key released    97(ks): a
DEBUG:Screenkey:Key pressed  65507(ks): None (Control_L, mask: 00000000)
```

Is it normal that it starts in the background and I can't close it by pressing `ctrl-c` ? 

I've asked in Elementary's [Gitter](https://gitter.im/elementary/houston) and [Slack](https://elementarycommunity.slack.com) what would be the right repository to report this issue in. There doesn't seem to be a "general" issue queue.

**Comment by wavexx** [comment]
On Wed, Jun 28 2017, Peter Uithoven wrote:
> That works!

Yes, as I wrote before, it's a bug in ElementaryOS.

> Is it normal that it starts in the background and I can't close it by
> pressing `ctrl-c` ?

Yes, screenkey detaches by default (you can control it in the system
tray). Use --no-detach to supress this behavior.

> I've asked in Elementary's
> [Gitter](https://gitter.im/elementary/houston) and
> [Slack](https://elementarycommunity.slack.com) what would be the right
> repository to report this issue in. There doesn't seem to be a
> "general" issue queue.

I tried as well, but I have no experience with ElementaryOS.
If you can, you should try to file a report somewhere and point their
staff to this page.

This is a major configuration issue with ElementaryOS.
It's going to break other programs as well.

**Comment by peteruithoven** [comment]
I've opened an ElementaryOS issue: https://bugs.launchpad.net/elementaryos/+bug/1701010

**Comment by thapakazi** [comment]
I am also able to get it fixed by un-setting the **XMODIFIERS** flag on **arch** **linux** ;)
![screenshot-20171113-20 23 18](https://user-images.githubusercontent.com/1695906/32730876-7f7671cc-c8b0-11e7-9926-66a00cbeb269.png)

**Comment by wavexx** [comment]
I wished there was some sort of "check my keyboard configuration setup" tool that verifies the coherence of these settings.

It seems that installing and removing input methods will leave users with a broken setup in *many* distros. I recently helped a colleague with mint as well...

**Comment by thapakazi** [comment]
lets make one, shall we ;)

**Comment by wavexx** [comment]
See #56, so closing this.
