### ISSUE TITLE
show keys on designated area?

### ISSUE THREAD

**Issue by biocyberman** [wavexx/screenkey#40]
Hi
This seems a very nice application. Here are my questions:

Keep the last 5 commands in a stack in this area? With smaller text size is preferable. This allows the audience to follow a tutorial easier.

Alright, many of my questions are already addressed in the latest version in this git repo. So I will close this for now.

**Comment by wavexx** [comment]
On Fri, Jan 20 2017, biocyberman wrote:
> This seems a very nice application. I am testing with version 0.2 from
> Ubuntu's 16.04 repository. Here are my questions:

Ubuntu is, sadly, not the same version as available on this repository.
You can try this version by either downloading the source or using this
ppa:

  http://www.webupd8.org/2016/05/tool-to-display-keystrokes-in.html

It would help a lot if you could file a bug on ubuntu on this.

**Comment by biocyberman** [comment]
I am now trying with the latest version on your github repo. I still want to keep my original question: 
 
> Keep the last 5 commands in a stack in this area? With smaller text size is preferable. 

So say last 5 previous command are smaller text, the current one is normal text.

**Comment by wavexx** [comment]
On Fri, Jan 20 2017, biocyberman wrote:
> I am now trying with the latest version on your github repo. I still want to keep my original question:
>
>     Keep the last 5 commands in a stack in this area? With smaller text size is preferable.
>
> So say last 5 previous command are smaller text, the current one is normal text.

There is some code in the works for this (screenkey --multiline) that
switches on multiple lines split by carriage return, but it's still
incomplete right now.
