### ISSUE TITLE
popup menu sometimes do not work

### ISSUE THREAD

**Issue by albfan** [wavexx/screenkey#42]
sometimes popup menu is not showed.

If I use something like

    $ screenkey --show-settings

popup always work.

I don't know how to debug this problem, since I cannot make `--gtk-debug` pass to screenkey module, where gtk initializes

**Comment by wavexx** [comment]
On Sun, Mar 19 2017, Alberto Fanjul wrote:
> I don't know how to debug this problem, since I cannot make
> `--gtk-debug` pass to screenkey module, where gtk initializes

Use --debug to see what's going on.

**Comment by wavexx** [comment]
Any news?

**Comment by albfan** [comment]
`--debug` do not show anything related to popup (is internal for screenkey). I would prefer something like `GTK_DEBUG=all` to see all operations underneath.

By now I'm using a more conservative evolution of screenkey that always work for popup, trying to configure that logging to apply on your fork and resolve this.

I want to use your transparency but want to add history (labels appearing on top of actual when sometime pass) something like:

https://camo.githubusercontent.com/60bae21b2b1b6bc4d457550ef30541640b4ccb83/68747470733a2f2f62726f6f6b686f6e672e6769746875622e696f2f6173736574732f696d616765732f6373636f76652e676966

**Comment by wavexx** [comment]
On Fri, Mar 24 2017, Alberto Fanjul wrote:
> `--debug` do not show anything related to popup (is internal for
> screenkey). I would prefer something like `GTK_DEBUG=all` to see all
> operations underneath.

But does it work correctly when you specify --debug?

GTK_DEBUG=all should work if you gtk is built with debug on. You might
need to force --no-detach (or --debug), but there's nothing special in
screenkey.

> By now I'm using a more conservative evolution of screenkey that
> always work for popup, trying to configure that logging to apply on
> your fork and resolve this.

I personally never had issues in my tests with the output not showing on
the screen. I can only think about the window manager not managing the
window hints correctly.

Which window manager are you using? DE? and possible distribution?

**Comment by albfan** [comment]
I'm using arch linux with GNOME.

I'm expecting to see some

Gtk-WARNING or similar but nothing happens, so I cannot find what' the problem

**Comment by wavexx** [comment]
On Sat, Mar 25 2017, Alberto Fanjul wrote:
> I'm using arch linux with GNOME.

Could you try to login with an openbox session and see if it does the
same?

Do you have multiple monitors?
Does it work from gnome when just one monitor is plugged?

> I'm expecting to see some Gtk-WARNING or similar but nothing happens,
> so I cannot find what' the problem

Gtk warnings are generally due to usage issues or severe problems in the
display server. This looks like either a subtle bug internal to Gtk or
something else.

You say that screenkey works perfectly if --show-settings is specified?
Could you try with screenkey --no-systray?

**Comment by albfan** [comment]
Yes I have tried show-settings and that makes it work. 

I will try rest of those test and tell you something

**Comment by wavexx** [comment]
Ping @albfan

**Comment by albfan** [comment]
Pong @wavexx. From what I see popup is only show when you request `--show-settings` so I really don't know what is this all about, isn't it?

So this remain the same

    screenkey  (do not show settings dialog)
    screenkey --show-settings (shows always the settings dialog)
