### ISSUE TITLE
Feature request : Mouse

### ISSUE THREAD

**Issue by ChameleonScales** [wavexx/screenkey#43]
key-mon is a good alternative but screenkey is much better for the keyboard.
Unfortunately key-mon can't hide all the keyboard buttons, there's at least one. This makes is pretty annoying if you want to use screenkey for the keyboard and key-mon for the mouse.
I could ask to key-mon to add a mouse-only option but the links to feature requests and bug reports (given [here](https://code.google.com/archive/p/key-mon/)) are dead and its development seems much less active, so I feel I have more chance to ask for a mouse feature here. Unless you know a program that shows only the mouse ?

**Comment by wavexx** [comment]
On Mon, Apr 17 2017, Caetano Veyssières wrote:
> want to use both programs. I could ask to key-mon to add a mouse-only
> option but the links to feature requests and bug reports (given
> [here](https://code.google.com/archive/p/key-mon/)) are dead and its
> development seems much less active, so I feel I have more chance to
> ask for a mouse feature here.

key-mon has also some issues with the mouse circling feature by the way,
and it's generally lagging a few ms behind on my machine because it
shows/hides/moves the window at each click, which involves the window
manager.

It's in the plan to have this in screenkey too. There is already code I
wrote last year to log mouse events, but I didn't get to implement the
visualization yet. 'been busy with other projects

**Comment by wavexx** [comment]
To answer the second part, I still use keymon, but I hide the status window (so I just get the circling) for now. Ugly hack, but does the job.

I also use gromit-mpx (https://github.com/bk138/gromit-mpx) to annotate the screen while teaching. Very useful.

**Comment by ChameleonScales** [comment]
Cool to know there's a plan for it.
If you make it happen, I have a suggestion for the display.
In addition to having some kind of mouse like this :
![](http://i.imgur.com/jEyMXbI.png)

we could have an option to show the buttons on top of the cursor.
I tried to figure a design that would be cristal clear about which button is pushed while not being too intrusive, and I think this could do it well :

![](http://i.imgur.com/QaTVyD3.png)

I do some video tutorials on Blender 3D and this would be much more useful than a mouse at the bottom of the screen because mouse buttons are really important in Blender and you're usually looking at the cursor when watching the video (and it probably applies to most programs).

Also thanks for Gromit-mpx, cool program.

**Comment by pdeman** [comment]
is there any update for the mouse using screenkey ?
can it record right and left click ?

**Comment by ChameleonScales** [comment]
@pdeman Yes, simply download and install the "feature mouse" branch from zaygraveyard's fork.
Here's the link : https://github.com/zaygraveyard/screenkey/tree/feature/mouse

**Comment by pdeman** [comment]
Hi, I have cloned the feature mouse branch, but when I run ./screenkey I don't have the mouse feature.
is there any option to activate it ?

**Comment by pdeman** [comment]
ok I found the option in preference but what it does is "activating" the "transparent black background" where the keyboard activity is shown. but it's not said mouse or whatever. it's just the transparent black background. no indication that it's a mouse event which "activated it", neither if it's the left or right mouse click.
is that normal ?

**Comment by ChameleonScales** [comment]
can you show a screenshot of your preferences ?

**Comment by pdeman** [comment]
actually it works when running from the main folder but not when running from 
build/scripts-2.7
I didn't see last time but I had a python error 

> Failed to open file 'images/released.png'

and of course the folder images is not in build/scripts

the icon is a little too much on the left but I'll play with the options to see if I can change the position

**Comment by ChameleonScales** [comment]
You can change the position of the mouse by changing the position of the entire panel.
Click on "Select Window or region" and draw a rectangle
If Position is set to top, bottom or center, the bar will use the rectangle as a screen and be displayed within it accordingly.
Alternatively, if you set Position to fixed, you will draw a rectangle that will delimit the bar itself (width and height).

**Comment by absorber** [comment]
@ChameleonScales did you do a PR of your mouse branch? I'm using it now and it's pretty good so far.
Though personally I'd also change the display to allow better discerning of quick consecutive mouse clicks. Perhaps a wave?

**Comment by ChameleonScales** [comment]
@absorber I'm not the one writing code here. I'm the one asking for features. @zaygraveyard is the one who made the fork. But yes there is a PR:
https://github.com/wavexx/screenkey/pull/65
