### ISSUE TITLE
can't launch screenkey downloaded from github

### ISSUE THREAD

**Issue by ChameleonScales** [wavexx/screenkey#46]
I can use screenkey when it's installed from the AUR but if I uninstall it, download it from Github and run the screenkey executable, I get these errors :
```
Traceback (most recent call last):
  File "./screenkey", line 9, in <module>
    from Screenkey import *
  File "/home/caetano/Installed_programs/screenkey-master/Screenkey/__init__.py", line 2, in <module>
    gettext.install('screenkey', unicode=True)
TypeError: install() got an unexpected keyword argument 'unicode'
```
I need to make it work because I want to use a fork.

**Comment by wavexx** [comment]
On Tue, Jun 27 2017, Caetano Veyssières wrote:
> Traceback (most recent call last):
>   File "./screenkey", line 9, in <module>
>     from Screenkey import *
>   File "/home/caetano/Installed_programs/screenkey-master/Screenkey/__init__.py", line 2, in <module>
>     gettext.install('screenkey', unicode=True)
> TypeError: install() got an unexpected keyword argument 'unicode'
> ```
> I need to make it work because I want to use a fork.

Try to make explicit the python version: python2.7 screenkey.py

**Comment by ChameleonScales** [comment]
Yes !
Thank you
