### ISSUE TITLE
XIM support

### ISSUE THREAD

**Issue by introlinux** [wavexx/screenkey#5]
Hi, it would be possible to include utf-8 support in screenkey? I have an spanish keyboard and when I try to write "áéíóú" screenkey writes ", a , e , e , o , u".

Thanks in advance.

**Comment by wavexx** [comment]
On 07/08/15 13:46, Antonio Sánchez wrote:

> Hi, it would be possible to include utf-8 support in screenkey? I have
> an spanish keyboard and when I try to write "áéíóú" screenkey writes ",
> a , e , e , o , u".

That's strange. I generally use an italian/german one, and it works.

Maybe there's some locale configuration issue?
I've set my system to en_US.UTF-8.

**Comment by introlinux** [comment]
My system is in es_ES.UTF-8.
With an italian configuration you can write, for example, "perché" (with
accent)?

2015-08-07 14:33 GMT+02:00 wavexx notifications@github.com:

**Comment by wavexx** [comment]
On 07/08/15 15:47, Antonio Sánchez wrote:

> My system is in es_ES.UTF-8.
> With an italian configuration you can write, for example, "perché" (with
> accent)?

I always keep my locale to en_US.UTF-8 (for convenience and no
translations), but if I just switch keyboard layout using setxkbmap.

It just works. I can type umlauts and accented letters just fine.

Can you attach a screenshot maybe to see exactly the output?

Also, can you run screenkey using -d to and attach a few lines of output
as well?

**Comment by introlinux** [comment]
I made a little video, might help to find out what happens.

Thank you for your patience.

2015-08-07 16:09 GMT+02:00 wavexx notifications@github.com:

**Comment by introlinux** [comment]
wop! http://youtu.be/-7-NtjPIqe4

2015-08-09 0:24 GMT+02:00 Antonio Sánchez introlinux@gmail.com:

**Comment by wavexx** [comment]
On 09/08/15 00:25, Antonio Sánchez wrote:

> wop! http://youtu.be/-7-NtjPIqe4

Thanks for the video, it was really helpful.

I cannot tell due to the low quality, but when do you press "à" for
example (and I assume), I see first \ufe51 seem to appear in the
"Symbols" output, quickly followed by a regular "a".

Right?

**Comment by wavexx** [comment]
On 09/08/15 01:21, Yuri D'Elia wrote:

> On 09/08/15 00:25, Antonio Sánchez wrote:
> 
> > wop! http://youtu.be/-7-NtjPIqe4
> 
> Thanks for the video, it was really helpful.
> 
> I cannot tell due to the low quality, but when do you press "à" for
> example (and I assume), I see first \ufe51 seem to appear in the
> "Symbols" output, quickly followed by a regular "a".

Ha, now I see.

I just tried the same with the es keyboard map: it's a composed sequence
with a dead key.

Composed sequences are not currently handled indeed (even though I use
the altgr-intl option regularly myself).

I need to read some documentation in order to handle it correctly.

**Comment by introlinux** [comment]
By default, youtube scale videos, chage the quality/resolution at the
botton right.

2015-08-09 1:29 GMT+02:00 wavexx notifications@github.com:

**Comment by wavexx** [comment]
This was true hell to fix, but it _should_ work correctly now.
Could you give the latest sources a try?

**Comment by introlinux** [comment]
You rocks! It goes perfectly now. :-)

**Comment by wavexx** [comment]
Then closing!
