### ISSUE TITLE
Feature request: Count of key strokes

### ISSUE THREAD

**Issue by kaihendry** [wavexx/screenkey#51]
Idea is to show how much input is required in some flows. If you know any other ways of doing it for a screencast, please let me know!

**Comment by wavexx** [comment]
Do you want a live running counter to be displayed, or just have an estimate for yourself? [I could think a couple of easy ways to do it for the latter]

**Comment by kaihendry** [comment]
Ideally on screen, nonetheless I'm interested in how to get an estimate!

**Comment by wavexx** [comment]
On Mon, Oct 16 2017, Kai Hendry wrote:
> Ideally on screen, nonetheless I'm interested in how to get an estimate!

Brutally, you can do the following from the command line:

  python ./Screenkey/inputlistener.py > keylog

to record the keypresses into a files. Then count them:

  grep "'pressed': True" keylog | wc -l

**Comment by wavexx** [comment]
Closing this, as it's not something I see directly useful in screenkey itself.
