### ISSUE TITLE
Add to snap or pip 

### ISSUE THREAD

**Issue by Zerokami** [wavexx/screenkey#55]
Currently the package is available only on Github.

Snap is a packing system that is available on all major Linux distros and there is also additional sandboxing.

Users can install a package like `sudo snap install screenkeey`.

**Comment by wavexx** [comment]
I'm against applications in pip (as a python developer I consider pip a repository of modules, not apps).
As for `snap`, I'm not against it, but I'm not a snap user - so help welcome.

**Comment by wavexx** [comment]
Made my mind, not going to do this. I'd rather have some people help with the ubuntu or debian packaging.
