### ISSUE TITLE
Custom key label replacements

### ISSUE THREAD

**Issue by numirias** [wavexx/screenkey#57]
It would be great to be able to use custom key label replacements or disable certain keys.

For example, I might want the sequence `Ctrl+Q` to be displayed as `[Close window]` or use other custom labels. Currently I'm just monkey-patching that, but I think it would be a nice feature. I'd understand if you consider that too much bloat, though.

**Comment by wavexx** [comment]
Somehow it would make sense for this to replace the current "keycap mode", which has only some built-in, hard-coded replacement maps for meta keys to specific symbols.
