### ISSUE TITLE
No tray icon in GNOME 17.10 (Wayland) when running detached

### ISSUE THREAD

**Issue by Snowman3456** [wavexx/screenkey#60]
```
 OPERATING SYSTEM:   Ubuntu 17.10
    Kernel:           4.15.0-041500rc4-generic (x86_64) 20171217
    Desktop:          GNOME Shell 3.26.2
    Display Server:   Wayland
    Compiler:         GCC 7.2.0
```

![tray](https://user-images.githubusercontent.com/4528283/34237949-447eae60-e5cd-11e7-8c61-772ba0194aea.png)

**Comment by wavexx** [comment]
What happens if you install the python-appindicator module?

**Comment by Snowman3456** [comment]
That works - that should be added to the Ubuntu/Debian dependency.

**Comment by wavexx** [comment]
On Thu, Dec 21 2017, Enigma wrote:
> That works - that should be added to the Ubuntu/Debian dependency.

I added a note in the readme. Appindicator is only required by gnome,
everything else will work with the regular GTK's status icon.
