### ISSUE TITLE
Missing support for wayland

### ISSUE THREAD

**Issue by albfan** [wavexx/screenkey#61]
Open gnome-terminal or terminator all the input goes to that windows, and nothing goes to screenkey

If you change to focus a browser or other kind of app, input goes again to screenkey

**Comment by wavexx** [comment]
I guess this is in wayland, right? It can be that gnome-terminal bypasses X11 entirely, and thus doesn't actually generate events screenkey can see.

**Comment by albfan** [comment]
Yes it is. Migrate to gtk3 would solve it? Why chrome do not capture input, neither other apps. What's the difference.

I can do a triage if you know a battery of apps to try with, is there any terminator that should work?

**Comment by wavexx** [comment]
On Thu, Dec 21 2017, Alberto Fanjul wrote:
> Yes it is. Migrate to gtk3 would solve it? Why chrome do not capture
> input, neither other apps. What's the difference.

I don't know the situation exactly, as I'm not going to try wayland
until I have a decent tiling window manager and server-side-decorations
everywhere, but it's unlikely this is ever going to work.

wayland has a different input model, and the inputlistener in screenkey
probably needs to be rewritten completely.

I'm not even sure server-side full input capture can actually be done in
wayland in the current state (I'd be happy to be proven wrong).

**Comment by albfan** [comment]
Will ask on GNOME forums for this, meanwhile:

![terminal-vs-browser](https://user-images.githubusercontent.com/220968/44944440-e7e5be00-add6-11e8-84ff-30a21e33140b.gif)

**Comment by albfan** [comment]
Using x11 it works correctly

![works-correctly-x11](https://user-images.githubusercontent.com/220968/44944811-b8867f80-addd-11e8-9aef-5b865fad4a8b.gif)
