### ISSUE TITLE
several lines of output

### ISSUE THREAD

**Issue by albfan** [wavexx/screenkey#62]
Is it possible to add several lines of output

With an almost transparent background and the right foreground, screencast will be much easy to follow

**Comment by wavexx** [comment]
There is ``--multiline``, but it's currently incomplete.

**Comment by albfan** [comment]
I see the option. If there's any WIP, please upload and I can try to finish it

If not a simple guideline here would be enough (if you have something in mind)

**Comment by wavexx** [comment]
There's not much missing. It's only that the multiline output needs a different way to size the output window, and some option combinations do not make sense when multiline is active.

Essentially, when multiline is active, the font size needs to be fixed, whereas now the size is a factor the window size and position instead.

**Comment by wavexx** [comment]
I'll try to give this a go before looking at the mouse stuff.

**Comment by albfan** [comment]
Would be nice to see something like that. I'm starting to make screencast and will test it throroughly
