### ISSUE TITLE
turn off screenkey

### ISSUE THREAD

**Issue by pdeman** [wavexx/screenkey#64]
Hi,

I tried "both ctrl keys" in the same time, both alt keys, both shift keys but none of them works.
I don't find how to turn off the screenkey service ...

**Comment by pdeman** [comment]
oh sorry I forgot to uninstall via apt-get remove.

not it uses only the one from github.

**Comment by pdeman** [comment]
actually it worked one time
 but now I have this:

> INFO:Screenkey:Shift+Shift  detected: screenkey disabled
or 

> INFO:Screenkey:Shift+Shift detected: screenkey disabled

but screenkey is still running ... I can't turn it off

**Comment by pdeman** [comment]
and I tried to change the font size and now I have both  ... small and large ...

**Comment by ziadkh0** [comment]
Try `killall screenkey`

**Comment by wavexx** [comment]
Shift+Shift or Ctrl+Ctrl or Alt+Alt will disable and re-enable screenkey at each press. They don't actually exit screenkey. To exit screenkey you need to go through the tray icon and select quit.

If you don't have a systray icon, you're probably missing some python modules. On ubuntu you *need* python-appindicator.

**Comment by pdeman** [comment]
ok I have the icon now thanks
