### ISSUE TITLE
Font size gets smaller during usage

### ISSUE THREAD

**Issue by Moini** [wavexx/screenkey#68]
I've started screenkey (master branch) from its directory.
Then I've selected a small area where the keys may appear.
Then I've switched to keysyms mode, because it was the first mode that showed Ctrl while I was dragging the mouse.

Then I used Ctrl left a couple of times, and each time the black bar had been faded out, and then reappeared, the font size got tinier and tinier.

**Comment by wavexx** [comment]
On Tue, May 01 2018, Moini wrote:
> Then I used Ctrl left a couple of times, and each time the black bar
> had been faded out, and then reappeared, the font size got tinier and
> tinier.

I'd be curious to see a video of this behavior !?

**Comment by Moini** [comment]
https://framadrive.org/s/drL92r7DLwoNYTb

**Comment by Moini** [comment]
On the next start, the font is still just as tiny. This is my config contents:

{"opacity": 0.8, "mods_only": false, "font_desc": "Sans Bold", "compr_cnt": 3, "screen": 0, "no_systray": false, "bg_color": "black", "vis_space": true, "position": "bottom", "key_mode": "keysyms", "vis_shift": false, "mods_mode": "normal", "ignore": [], "font_size": "medium", "recent_thr": 0.1, "bak_mode": "baked", "geometry": [404, 815, 286, 77], "multiline": false, "timeout": 2.5, "persist": false, "font_color": "white"}

This is on Linux Mint 18.3 with Xfce.

**Comment by wavexx** [comment]
On Wed, May 02 2018, Moini wrote:
> https://framadrive.org/s/drL92r7DLwoNYTb

"Nice!". Ok, I was able to get exactly the same behavior.

**Comment by Moini** [comment]
I love it when weird issues are at least reproducible ;-) Thanks!

**Comment by wavexx** [comment]
Took me quite a while to get this to reproduce a second time.

*But*, the tiny label is "intended". What it's doing is this: it's placing the label at the *bottom* of the area you've selected. Select "fixed" from the drop-down and try again: it should do what you need.

I have to say, I don't particularly like the behavior either. I'll see if I can improve it a bit by detecting if you selected a window or an area and do The Right Thing(tm).

**Comment by wavexx** [comment]
Let's leave this open until the behavior is improved.

**Comment by wavexx** [comment]
Ok, I think the new behavior is much cleaner. Whenever you select a region, the mode switches to "fixed" automatically.

Could you give it a try?

**Comment by Moini** [comment]
Yes, that works. Thanks!
