### ISSUE TITLE
Opacity slider has no functionality

### ISSUE THREAD

**Issue by Moini** [wavexx/screenkey#71]
Hi there - just tested the opacity slider, and nothing happened, except for 

`  File "/tmp/screenkey-master/Screenkey/screenkey.py", line 191, in on_expose
    ctx.set_operator(cairo.Operator.SOURCE)
AttributeError: 'module' object has no attribute 'Operator'
`
when I move it.

Unrelated: screenkey ate my text cursor... just noticed while typing here. Can't reproduce it now. I couldn't type, and while the mouse worked normally for selecting text etc., clicking into the text didn't produce a blinking cursor. Only when I quit screenkey, I got my cursor back.

Unrelated, too: what's the functionality of the second color field in the settings dialog? It doesn't seem to change anything.

**Comment by wavexx** [comment]
On Sun, May 06 2018, Moini wrote:
> Hi there - just tested the opacity slider, and nothing happened, except for
>
> `  File "/tmp/screenkey-master/Screenkey/screenkey.py", line 191, in on_expose
>     ctx.set_operator(cairo.Operator.SOURCE)
> AttributeError: 'module' object has no attribute 'Operator'
> `
> when I move it.

Could you try again with the updated sources?

> Unrelated: screenkey ate my text cursor... just noticed while typing
> here. Can't reproduce it now. I couldn't type, and while the mouse
> worked normally for selecting text etc., clicking into the text didn't
> produce a blinking cursor. Only when I quit screenkey, I got my cursor
> back.
>
> Unrelated, too: what's the functionality of the second color field in
> the settings dialog? It doesn't seem to change anything.

Probably both issues are related with the above error.

**Comment by wavexx** [comment]
As mentioned, you'll need pycairo. Can you confirm it works once it is installed?

**Comment by Moini** [comment]
Do you know which package that corresponds to?

I get these:

> apt-cache search pycairo  
> python-cairo-dev - Python cairo bindings: development files  
> python-cairocffi - cffi-based cairo bindings for Python  
> python-cairocffi-doc - cffi-based cairo bindings for Python - Documentation  
> python3-cairocffi - cffi-based cairo bindings for Python (Python3)

Edit:
and these:

> apt-cache search python cairo
> python-cairo - Python bindings for the Cairo vector graphics library
> python-cairo-dbg - Python bindings for the Cairo vector graphics library (debug extension)
> python-cairo-dev - Python cairo bindings: development files
> python-scour - SVG scrubber and optimizer (Python 2 module)
> python3-cairo - Python 3 bindings for the Cairo vector graphics library
> python3-cairo-dev - Python 3 cairo bindings: development files
> python3-cairo-doc - Python 3 cairo bindings: documentation files
> python3-gi-cairo - Python 3 Cairo bindings for the GObject library
> cairo-dock-plug-ins-dbus-interface-python - Python interface to interact with Cairo-Dock by using DBus
> labyrinth - lightweight mind-mapping tool
> pybootchartgui - boot sequence visualisation
> python-cairocffi - cffi-based cairo bindings for Python
> python-cairocffi-doc - cffi-based cairo bindings for Python - Documentation
> python-cairosvg - SVG to PDF/PS/PNG converter based on Cairo
> python-gasp - procedural Python graphics library for beginning programmers
> python-gi-cairo - Python Cairo bindings for the GObject library
> python-hippocanvas - Python bindings to hippo-canvas
> python-igraph - High performance graph data structures and algorithms
> python-pycha - chart-drawing library using Cairo                                                                                            
> python3-cairocffi - cffi-based cairo bindings for Python (Python3)                                                                          
> python3-cairosvg - SVG to PDF/PS/PNG converter based on Cairo (Python3 library)                                                             
> xdot - interactive viewer for Graphviz dot files                                                                                            
> screenlets - Widget-like mini-applications for GNOME

**Comment by Moini** [comment]
Which I had installed. It's python2, right?

**Comment by Moini** [comment]
Works. It wasn't pycairo, but the fix :) Thanks!
Could it be made clearer that the second color selector is for the background color? It has no description of its own.

**Comment by wavexx** [comment]
On Mon, May 07 2018, Moini wrote:
> Works. It wasn't pycairo, but the fix :) Thanks!
> Could it be made clearer that the second color selector is for the background color? It has no description
> of its own.

Tooltip?

**Comment by Moini** [comment]
Would work for me. 

I know the Gnome people removed all tooltips from the new apps, so things work on a tablet where there exists no 'hover' (and replaced them with unintellegible icons... horrible!). 

It could also just be a second row with a text in front, that would work for everyone, with or without hovering.
