### ISSUE TITLE
Feature request : mouse actions around cursor

### ISSUE THREAD

**Issue by ChameleonScales** [wavexx/screenkey#73]
Splitting from #65.
Here's a recap :
I'd like to display mouse actions (LMB, MMB, RMB, scrolling) around the cursor instead of inside the screenkey box. This would make the viewer's experience smoother and easier to follow, as he wouldn't have to jump his attention back and fourth between the cursor and the mouse icon.

Here's the design I propose for it :
![](https://i.imgur.com/OoCE35P.png)

in more details, the icons would appear on press and would fade out on release, possibly scaling up during fading.
Their color should be customizable so that they could be visible in any environment.

**Comment by gwpl** [comment]
I wondered if this example source code:

* https://unix.stackexchange.com/a/228674/9689
* https://github.com/Carpetsmoker/find-cursor

finding and displaying cursor,
plus:
monitoring mouse clicks may be inspirted by backtracking from here:

* https://github.com/rcaelers/workrave/blob/6bebb7f8e57821c31f1bb1176a8b016d3bfc55b4/backend/src/Statistics.cc#L1079
