### ISSUE TITLE
Move to GitLab

### ISSUE THREAD

**Issue by wavexx** [wavexx/screenkey#76]
I'll be moving my source repositories to GitLab (https://gitlab.com/wavexx/) during the next few days.

I've been waiting to do this for a long time (at least since 2015) but I never switched because of network effects. I'll now use the acquisition news as an excuse to jump the shark!

This repository will be turned into a read-only archive after the migration and effectively become stale.
Since all issues and PR will be mirrored on gitlab, I'll also close all of them in github and reference this issue to make sure this is not going to be ignored. 

See you on the other side!

**Comment by Moini** [comment]
Can you tag me as @Moini on gitlab, please? Then it's going to be easier to find :)
