### ISSUE TITLE
Tray icon missing in Ubuntu 18.04

### ISSUE THREAD

**Issue by george-viaud** [wavexx/screenkey#82]
Installed from default apt repo.

Missing tray icon - otherwise works great.

**Comment by wavexx** [comment]
See #60

**Comment by wavexx** [comment]
From where did you install screenkey? Ubuntu universe?
Please file a bug on ubuntu about a missing dependency.

Debian doesn't have unity, so the dependency cannot be added on the original package.

**Comment by george-viaud** [comment]
Indeed, addin `python-appindicator` solved my problem.
I installed from Universe indeed.
18.04 isn't running Unity so I guess when installed to 17.10+ apt should force `python-appindicator` ?  I'll see if I can find the package manager (person) and ask them to add.

Thanks!

**Comment by george-viaud** [comment]
Bug opened on package site https://bugs.launchpad.net/ubuntu/+source/screenkey/+bug/1795809

Thanks again

**Comment by wavexx** [comment]
On Wed, Oct 03 2018, George Viaud wrote:
> 18.04 isn't running Unity so I guess when installed to 17.10+ apt
> should force python-appindicator ? I'll see if I can find the package
> manager (person) and ask them to add.

It really depends on which desktop manager you're using. The regular
systray works everywhere else except gnome, so I wouldn't consider this
strictly as a bug. Ideally this would be a "recommended" package on
Ubuntu.

One of the many reasons I came to dislike anything gnome.
